PB\VentasBundle\Entity\AlbaranLinea:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        referencia:
            type: string
            length: '50'
            nullable: true
        numlinea:
            type: integer
            nullable: true
        codpedido:
            type: integer
            nullable: true
        ancho:
            type: string
            length: '50'
            nullable: true
        largo:
            type: integer
            nullable: true
        galga:
            type: integer
            nullable: true
        solapa:
            type: integer
            nullable: true
        descripcion:
            type: string
            length: 255
            nullable: true
        cantidad:
            type: float
            nullable: true
        precio:
            type: float
            nullable: true
        descuento: 
            type: float
            nullable: true
        importe:
            type: float
            nullable: true
    manyToOne:
        albaran:
            targetEntity: PB\VentasBundle\Entity\Albaran
            inversedBy: albaranlineas
            cascade: [persist]
            joinColumn:
                name: albaran_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
