PB\VentasBundle\Entity\Albaran:
    type: entity
    table: null
    repositoryClass: PB\VentasBundle\Repository\AlbaranRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fecha:
            type: date
            nullable: true
        fecha_entrega:
            type: date
            nullable: true
        tipo:
            type: smallint
            nullable: true
        codfactura:
            type: smallint
            nullable: true
        iva:
            type: smallint
        descuento:
            type: smallint
            nullable: true
        recargo:
            type: boolean
            nullable: true
        anyo:
            type: integer
            nullable: true
        importetotal:
            type: float
            nullable: true
        observaciones:
            type: text
            nullable: true
    manyToOne:
        cliente:
            targetEntity: PB\VentasBundle\Entity\Cliente
            inversedBy: albaran
            joinColumn:
                name: cliente_id
                referencedColumnName: id
    oneToMany:
        albaranlineas:
            targetEntity: PB\VentasBundle\Entity\AlbaranLinea
            mappedBy: albaran  
            cascade: [ persist ]  
    lifecycleCallbacks:
        prePersist: [ setAnyoPre ]