PB\VentasBundle\Entity\Presupuesto:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fecha:
            type: date
            nullable: true
        coutaiva:
            type: smallint
            nullable: true
        iva:
            type: smallint
        nombre:
            type: string
            length: '50'
            nullable: true
        descuento:
            type: smallint
            nullable: true
        importetotal:
            type: float
            nullable: true
        observaciones:
            type: text
            nullable: true
    manyToOne:
        cliente:
            targetEntity: PB\VentasBundle\Entity\Cliente
            inversedBy: presupuesto
            joinColumn:
                name: cliente_id
                referencedColumnName: id
    oneToMany:
        presupuestolineas:
            targetEntity: PB\VentasBundle\Entity\PresupuestoLinea
            mappedBy: presupuesto 
            cascade: [ persist ]  
    lifecycleCallbacks:
        prePersist: [  ]