<?php

namespace PB\ProduccionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExtrusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtrusionRepository extends EntityRepository
{
	public function getExtrusion($maquina)
	{
		$query = $this->getEntityManager()
		->createQuery('SELECT e FROM PBProduccionBundle:Extrusion e	WHERE e.maquina = :id')->setParameter('id', $maquina);
		$result = $query->getResult();
		return $result;
		/*
		if($result) {
			return $result->getId();
		} else {
			return '';
		}*/
	}
}
