<?php

namespace PB\ProduccionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExtrusionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtrusionRepository extends EntityRepository
{
}
