cliente:
    pattern:  /
    defaults: { _controller: "PBVentasBundle:Cliente:index" }

buscador_cliente:
    pattern:  /buscador
    defaults: { _controller: "PBVentasBundle:Cliente:buscadorCliente" }

get_nombre_cliente:
    pattern:  /getnombre
    defaults: { _controller: "PBVentasBundle:Cliente:getNombre", _format: json }
    requirements:
        _format: (xml|json)
        _method:  POST
        
cliente_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBVentasBundle:Cliente:show" }

cliente_new:
    pattern:  /new
    defaults: { _controller: "PBVentasBundle:Cliente:new" }

cliente_create:
    pattern:  /create
    defaults: { _controller: "PBVentasBundle:Cliente:create" }
    requirements: { _method: post }

cliente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBVentasBundle:Cliente:edit" }

cliente_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBVentasBundle:Cliente:update" }
    requirements: { _method: post }

cliente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBVentasBundle:Cliente:delete" }
    requirements: { _method: post }
