pedido:
    pattern:  /
    defaults: { _controller: "PBVentasBundle:Pedido:index" }

pedido_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBVentasBundle:Pedido:show" }

pedido_print:
    pattern:  /{id}/print
    defaults: { _controller: "PBVentasBundle:Pedido:imprimir" }

pedido_new:
    pattern:  /new
    defaults: { _controller: "PBVentasBundle:Pedido:new" }

pedido_create:
    pattern:  /create
    defaults: { _controller: "PBVentasBundle:Pedido:create" }
    requirements: { _method: post }

pedido_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBVentasBundle:Pedido:edit" }

pedido_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBVentasBundle:Pedido:update" }
    requirements: { _method: post }

pedido_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBVentasBundle:Pedido:delete" }
    requirements: { _method: post }

buscador_pedidos_cliente:
    pattern:  /pedidos_cliente/{id}
    defaults: { _controller: "PBVentasBundle:Pedido:buscadorPedidosCliente" }

get_pedido:
    pattern:  /getpedido
    defaults: { _controller: "PBVentasBundle:Pedido:getPedido", _format: json }
    requirements:
        _format: (xml|json)
        _method:  POST