pedidocliente:
    pattern:  /
    defaults: { _controller: "PBVentasBundle:PedidoCliente:index" }

pedidocliente_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBVentasBundle:PedidoCliente:show" }

pedidocliente_new:
    pattern:  /new
    defaults: { _controller: "PBVentasBundle:PedidoCliente:new" }

pedidocliente_create:
    pattern:  /create
    defaults: { _controller: "PBVentasBundle:PedidoCliente:create" }
    requirements: { _method: post }

pedidocliente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBVentasBundle:PedidoCliente:edit" }

pedidocliente_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBVentasBundle:PedidoCliente:update" }
    requirements: { _method: post }

pedidocliente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBVentasBundle:PedidoCliente:delete" }
    requirements: { _method: post }
    
pedidocliente_print:
    pattern:  /{id}/print
    defaults: { _controller: "PBVentasBundle:PedidoCliente:print" }

pedidocliente_mail:
    pattern:  /{id}/mail
    defaults: { _controller: "PBVentasBundle:PedidoCliente:mail" }
    
pedidocliente_duplicar:
    pattern:  /{id}/duplicar
    defaults: { _controller: "PBVentasBundle:PedidoCliente:duplicar" }

pedidocliente_duplicar_guardar:
    pattern:  /{id}/duplicarguardar
    defaults: { _controller: "PBVentasBundle:PedidoCliente:duplicarGuardar" }
    requirements: { _method: post }

pedidocliente_fabricar:
    pattern:  /{id}/fabricar
    defaults: { _controller: "PBVentasBundle:PedidoCliente:fabricar" }

pedidocliente_fabricar_guardar:
    pattern:  /{id}/fabricarguardar
    defaults: { _controller: "PBVentasBundle:PedidoCliente:fabricarGuardar" }
    requirements: { _method: post }

pedidocliente_show_lightbox:
    pattern:  /{id}/showLightbox
    defaults: { _controller: "PBVentasBundle:PedidoCliente:showLightbox" }

buscador_pedidos_cliente2:
    pattern:  /pedidos_cliente/{id}
    defaults: { _controller: "PBVentasBundle:PedidoCliente:buscadorPedidosCliente" }