presupuesto:
    pattern:  /
    defaults: { _controller: "PBVentasBundle:Presupuesto:index" }

presupuesto_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBVentasBundle:Presupuesto:show" }

presupuesto_prenew:
    pattern:  /prenew
    defaults: { _controller: "PBVentasBundle:Presupuesto:prenew" }

presupuesto_new:
    pattern:  /new
    defaults: { _controller: "PBVentasBundle:Presupuesto:new" }

presupuesto_create:
    pattern:  /create
    defaults: { _controller: "PBVentasBundle:Presupuesto:create" }
    requirements: { _method: post }

presupuesto_preedit:
    pattern:  /{id}/preedit
    defaults: { _controller: "PBVentasBundle:Presupuesto:preedit" }

presupuesto_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBVentasBundle:Presupuesto:edit" }

presupuesto_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBVentasBundle:Presupuesto:update" }
    requirements: { _method: post }

presupuesto_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBVentasBundle:Presupuesto:delete" }
    requirements: { _method: post }

presupuesto_print:
    pattern:  /{id}/print
    defaults: { _controller: "PBVentasBundle:Presupuesto:imprimir" }
    
presupuesto_mail:
    pattern:  /{id}/mail
    defaults: { _controller: "PBVentasBundle:Presupuesto:mail" }