PB\InicioBundle\Entity\Provincias:
    type: entity
    table: provincias
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        codprovincia:
            type: string
            length: 10
            fixed: false
            nullable: false
        denprovincia:
            type: string
            length: 100
            fixed: false
            nullable: false
    oneToMany:
        provincia2:
            targetEntity: PB\VentasBundle\Entity\Cliente
            mappedBy: provincia_cliente
            unique: false
        provincia4:
            targetEntity: PB\ComprasBundle\Entity\Proveedor
            mappedBy: provincia_proveedor
            unique: false
        provincia3:
            targetEntity: PB\VentasBundle\Entity\Comercial
            mappedBy: provincia_comercial           
    lifecycleCallbacks: {  }
