PB\InicioBundle\Entity\Provincias:
    type: entity
    table: provincias
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        codprovincia:
            type: string
            length: 10
            fixed: false
            nullable: false
        denprovincia:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
