pb_almacen:
    resource: "@PBAlmacenBundle/Resources/config/routing.yml"
    prefix:   /almacen

pb_contabilidad:
    resource: "@PBContabilidadBundle/Resources/config/routing.yml"
    prefix:   /contabilidad

pb_produccion:
    resource: "@PBProduccionBundle/Resources/config/routing.yml"
    prefix:   /produccion

pb_general:
    resource: "@PBGeneralBundle/Resources/config/routing.yml"
    prefix:   /general

PBVentasBundle:
    resource: "@PBVentasBundle/Resources/config/routing.yml"
    prefix:   /ventas

PBComprasBundle:
    resource: "@PBComprasBundle/Resources/config/routing.yml"
    prefix:   /compras

PBInicioBundle:
    resource: "@PBInicioBundle/Resources/config/routing.yml"
    prefix:   /inicio

_welcome:
    pattern:  /
    defaults: { _controller: PBInicioBundle:Default:index }

login:
    pattern: /login
    defaults: { _controller: PBInicioBundle:Security:login }
 
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


