PB\ProduccionBundle\Entity\Extrusion:
  type: entity
  table: null
  repositoryClass: PB\ProduccionBundle\Repository\ExtrusionRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    inicio:
      type: datetime
      nullable: true
    fin:
      type: datetime
      nullable: true
    estado:
      type: smallint
    tipomaterial:
      type: smallint
    color:
      type: string
      lenght: 55
      nullable: true
    ancho:
      type: integer
    galga:
      type: integer
    plegado:
      type: integer
      nullable: true
    tratado:
      type: smallint
      nullable: true
    metros:
      type: integer
    bobinas:
      type: integer
      nullable: true
    pesoneto:
      type: float
    pesoteorico:
      type: float
  manyToOne:
    maquina:
      targetEntity: PB\ProduccionBundle\Entity\Maquina
      inversedBy: extrusion
      joinColumn:
        name: maquina_id
        referencedColumnName: id
  oneToMany:
    ordenes:
      targetEntity: PB\ProduccionBundle\Entity\orden
      mappedBy: extrusion_orden  
      cascade: [ persist ]  
  lifecycleCallbacks: {  }
