proveedor:
    pattern:  /
    defaults: { _controller: "PBComprasBundle:Proveedor:index" }
    
buscador_proveedor:
    pattern:  /buscador
    defaults: { _controller: "PBComprasBundle:Proveedor:buscadorProveedor" }

get_nombre_proveedor:
    pattern:  /getnombre
    defaults: { _controller: "PBComprasBundle:Proveedor:getNombre", _format: json }
    requirements:
        _format: (xml|json)
        _method:  POST

proveedor_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBComprasBundle:Proveedor:show" }

proveedor_new:
    pattern:  /new
    defaults: { _controller: "PBComprasBundle:Proveedor:new" }

proveedor_create:
    pattern:  /create
    defaults: { _controller: "PBComprasBundle:Proveedor:create" }
    requirements: { _method: post }

proveedor_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBComprasBundle:Proveedor:edit" }

proveedor_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBComprasBundle:Proveedor:update" }
    requirements: { _method: post }

proveedor_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBComprasBundle:Proveedor:delete" }
    requirements: { _method: post }

proveedor_csv:
    pattern:  /csv
    defaults: { _controller: "PBComprasBundle:Proveedor:csv" }
