proveedor:
    pattern:  /
    defaults: { _controller: "PBComprasBundle:Proveedor:index" }

proveedor_show:
    pattern:  /{id}/show
    defaults: { _controller: "PBComprasBundle:Proveedor:show" }

proveedor_new:
    pattern:  /new
    defaults: { _controller: "PBComprasBundle:Proveedor:new" }

proveedor_create:
    pattern:  /create
    defaults: { _controller: "PBComprasBundle:Proveedor:create" }
    requirements: { _method: post }

proveedor_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PBComprasBundle:Proveedor:edit" }

proveedor_update:
    pattern:  /{id}/update
    defaults: { _controller: "PBComprasBundle:Proveedor:update" }
    requirements: { _method: post }

proveedor_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PBComprasBundle:Proveedor:delete" }
    requirements: { _method: post }
