tipo_proveedor:
  0: "Indefinido"
  1: "Materia Prima"
  2: "Servicios"
  3: "Materiales Auxiliares"
  4: "Reparación y Conservación"
  5: "Otros Servicios"
  
medio_envio:
  0: "Indefinida"
  1: "Agencia"
  2: "Transporte propio"
  3: "Internacional"

estados:
  1: "Enviado"
  2: "Recibido OK"
  3: "Recibido con Erorres"
  4: "Rechazado"