tipo_proveedor:
  0: ""
  1: "Materia Prima"
  6: "Polipropileno"
  7: "Tintas y Disolventes"
  8: "Cliches"
  10: "Canutos"
  11: "Precinto"
  12: "Retractil"
  2: "Servicios"
  3: "Materiales Auxiliares"
  4: "Reparación y Conservación"
  9: "Material de Oficina"
  5: "Otros Servicios"
  
medio_envio:
  0: ""
  1: "Agencia"
  2: "Transporte propio"
  3: "Internacional"

estados:
  1: "Enviado"
  5: "En Proceso"
  2: "Recibido OK"
  3: "Recibido con Erorres"
  4: "Rechazado"

tipo_evaluacion:
  1: "Histórico"
  2: "A Prueba"
  3: "Certificado"
  4: "Por exclusividad"

incidencias_compras:
  1: "Pérdida de un Pedido imputable a incumplimiento o Fallo de Proveedor"
  2: "Materiales no entregados"
  3: "Materiales entregados con retraso"
  4: "Entrega de material defectuoso o de inferior calidad"
  5: "Criterios de Dirección"
  6: "Rechazo de un pedido por parte del cliente debido a la calidad de los materiales utilizados"
  7: "Repeticiones de un pedido por errores"
  8: "Parada o avería de algún equipo de producción imputable a la mala calidad de la materia prima"