PBComprasBundle_homepage:
    pattern:  /compras
    defaults: { _controller: PBComprasBundle:Default:index }

PBComprasBundle_proveedor:
    resource: "@PBComprasBundle/Resources/config/routing/proveedor.yml"
    prefix:   /proveedor

PBComprasBundle_compras_pedidocompra:
    resource: "@PBComprasBundle/Resources/config/routing/pedidocompra.yml"
    prefix:   /pedidocompra
