parameters:
#    pb_compras.example.class: PB\ComprasBundle\Example

services:
#    pb_compras.example:
#        class: %pb_compras.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pb_compras.type.proveedor_id:
        class: PB\ComprasBundle\Form\Type\ProveedorIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: proveedor_text }
