PB\ComprasBundle\Entity\Proveedor:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: email
            message: Existe otro proveedor con ese email
    properties:
        nombre:
            - NotBlank: ~
            - MinLength: 3
            - NotNull: ~
        nif:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        cp:
            - NotBlank: ~
            - Type:
                type: numeric
                message: El codigo postal no es un número.
        localidad:
            - NotBlank: ~
        email:
            - Email:
                message: El Email "{{ value }}" no es válido.
                
PB\ComprasBundle\Entity\PedidoCompra:
    properties:
        fecha:
            - NotBlank:  { message: "El campo 'Fecha' esta vacio."}
        fecha_entrega:
            - NotBlank:  { message: "El campo 'Fecha Entrega' esta vacio."}
        proveedor:
            - NotBlank:  { message: "El campo 'Proveedor' esta vacio."}
PB\ComprasBundle\Entity\PedidoCompraLinea:
    properties:
        descripcion:
            - NotBlank:  { message: "El campo 'Descripcion' esta vacio."}