PB\ComprasBundle\Entity\Proveedor:
    properties:
        nombre:
            - NotBlank: ~
            - MinLength: 3
            - NotNull: ~
        nif:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        cp:
            - NotBlank: ~
            - Type:
                type: numeric
                message: El codigo postal no es un número.
        localidad:
            - NotBlank: ~
PB\ComprasBundle\Entity\PedidoCompra:
    properties:
        fecha:
            - NotBlank:  { message: "El campo 'Fecha' esta vacio."}
        fecha_entrega:
            - NotBlank:  { message: "El campo 'Fecha Entrega' esta vacio."}
        proveedor:
            - NotBlank:  { message: "El campo 'Proveedor' esta vacio."}
PB\ComprasBundle\Entity\PedidoCompraLinea:
    properties:
        descripcion:
            - NotBlank:  { message: "El campo 'Descripcion' esta vacio."}