PB\ComprasBundle\Entity\Proveedor:
    properties:
        nombre:
            - NotBlank: ~
            - MinLength: 3
            - NotNull: ~
        nif:
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        cp:
            - NotBlank: ~
            - Type:
                type: numeric
                message: El codigo postal no es un número.
        localidad:
            - NotBlank: ~