PB\ComprasBundle\Entity\AlbaranCompraLinea:
  type: entity
  table: null
  repositoryClass: PB\ComprasBundle\Repository\AlbaranCompraLineaRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    referencia:
      type: string
      length: 255
      nullable: true
    descripcion:
      type: string
      length: 255
      nullable: true
    cantidad:
      type: float
      nullable: true
    precio:
      type: float
      nullable: true
    descuento:
      type: float
      nullable: true
    total:
      type: float
      nullable: true
    estado:
      type: smallint
      nullable: true
  manyToOne:
    albarancompralinea:
      targetEntity: PB\ComprasBundle\Entity\AlbaranCompra
      inversedBy: albarancompralineas
      joinColumn:
        name: albarancompra_id
        referencedColumnName: id
        onDelete: CASCADE
  oneToMany:
    almacen:
      targetEntity: PB\AlmacenBundle\Entity\Almacen
      mappedBy: albarancompralinea
  lifecycleCallbacks: {  }
