PB\ComprasBundle\Entity\PedidoCompra:
  type: entity
  repositoryClass: PB\ComprasBundle\Repository\PedidoCompraRepository
  table: PedidoCompra
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    fecha:
      type: date
    fecha_entrega:
      type: date
      nullalble: true
    referencia:
      type: string
      length: '100'
      nullable: true
    forma_envio:
      type: integer
      nullable: true
    importe:
      type: float
      nullable: true
    total:
      type: float
      nullable: true
    iva:
      type: smallint
      nullable: true
    descuento:
      type: float
      nullable: true
  manyToOne:
    proveedor:
      targetEntity: PB\ComprasBundle\Entity\Proveedor
      inversedBy: pedidocompra
      joinColumn:
        name: proveedor_id
        referencedColumnName: id
  oneToMany:
    pedidocompralineas:
        targetEntity: PB\ComprasBundle\Entity\PedidoCompraLinea
        mappedBy: pedidocompralinea
        cascade: [ persist ]
        
  lifecycleCallbacks: {  }
