PB\ComprasBundle\Entity\Proveedor:
  type: entity
  repositoryClass: PB\ComprasBundle\Repository\ProveedorRepository
  table: proveedores
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    codproveedor:
      type: string
      length: 50
      nullable: true
    nombre:
      type: string
      length: 255
    nombrecomercial:
      type: string
      length: 255
      nullable: true
    nif:
      type: string
      length: '50'
    nombrecontacto:
      type: string
      length: 255
      nullable: true
    telefono_contacto:
      type: integer
      nullable: true
    email_contacto:
      type: string
      length: 255
      nullable: true
    telefono:
      type: bigint
      nullable: true
    telefono2:
      type: bigint
      nullable: true
    fax:
      type: bigint
      nullable: true
    email:
      type: string
      length: 255
      unique: true
      nullable: true
    web:
      type: string
      length: 255
      nullable: true
    direccion:
      type: string
      length: 255
    cp:
      type: integer
    localidad:
      type: string
      length: 255
    pais:
      type: string
      lenght: 100
      nullable: true
    tipo_proveedor:
      type: smallint
      nullable: true
    es_cliente:
      type: boolean
      nullable: true
    activo:
      type: boolean
      nullable: true
    observaciones:
      type: text
      nullable: true
    medio_envio:
      type: smallint
      nullable: true
    paga_iva:
      type: boolean
      nullable: true
    irpf:
      type: boolean
      nullable: true
    codigo_externo:
      type: smallint
      nullable: true
    cuenta_bancaria:
      type: string
      nullable: true
    codigo_contabilidad:
      type: string
      nullable: true
    fechaalta:
      type: date
      nullable: true
  manyToOne:
    formapago_proveedor:
      targetEntity: PB\GeneralBundle\Entity\FormaPago
      inversedBy: formapagos
      joinColumn:
        name: formapago_id
        referencedColumnName: id
    provincia_proveedor:
      targetEntity: PB\InicioBundle\Entity\Provincias
      inversedBy: provincia4
      joinColumn:
        name: provincia_id
        referencedColumnName: id
  oneToMany:
    pedidocompra:
        targetEntity: PB\ComprasBundle\Entity\PedidoCompra
        mappedBy: proveedor
  lifecycleCallbacks: 
    prePersist: [ setFechaAltaPre ]