parameters:
#    pb_contabilidad.example.class: PB\ContabilidadBundle\Example

services:
#    pb_contabilidad.example:
#        class: %pb_contabilidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
