pb_produccion_homepage:
    pattern:  /
    defaults: { _controller: PBProduccionBundle:Default:index }

produccion_maquinaria:
    pattern:  /maquinaria
    defaults: { _controller: PBProduccionBundle:Default:maquinaria }

PBProduccionBundle_orden:
    resource: "@PBProduccionBundle/Resources/config/routing/orden.yml"
    prefix:   /orden

PBProduccionBundle_maquina:
    resource: "@PBProduccionBundle/Resources/config/routing/maquina.yml"
    prefix:   /maquina

PBProduccionBundle_extrusion:
    resource: "@PBProduccionBundle/Resources/config/routing/extrusion.yml"
    prefix:   /extrusion
