pb_calidad_homepage:
    pattern:  /
    defaults: { _controller: PBCalidadBundle:Default:index }

PBCalidadBundle_noconformidad:
    resource: "@PBCalidadBundle/Resources/config/routing/noconformidad.yml"
    prefix:   /noconformidad
