PB\CalidadBundle\Entity\Noconformidad:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fecha_apertura:
            type: date
        descripcion:
            type: text
        acciones_inmediatas:
            type: text
        analisis_causas:
            type: text
        acciones:
            type: text
            nullable: true
        responsable:
            type: string
            length: 255
        plazo:
            type: string
            length: 255
            nullable: true
        fecha_cierre:
            type: date
            nullable: true
        explicacion:
            type: text
            nullable: true
        estado:
            type: smallint
    manyToOne:
        cliente:
            targetEntity: PB\VentasBundle\Entity\Cliente
            inversedBy: noconformidad
            joinColumn:
                name: cliente_id
                referencedColumnName: id
        pedidocliente:
            targetEntity: PB\VentasBundle\Entity\PedidoCliente
            inversedBy: noconformidad
            joinColumn:
                name: pedidocliente_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
