<?php

namespace PB\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbaranRepository extends EntityRepository
{
	
	public function getAlbaranidBycodfactura($codfactura)
	{
		
		$query = $this->getEntityManager()
		->createQuery('SELECT a FROM PBVentasBundle:Albaran a	WHERE a.codfactura = :id')->setParameter('id', $codfactura);
		$result = $query->getOneOrNullResult();
		if($result) {
			return $result->getId();
		} else {
			return '';
		}
	}
}
