<?php

namespace PB\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
	public function getClientes($limit = 20) {
		$dql = 'Select c from PBVentasBundle:Cliente c ORDER BY c.id DESC';
		
		$query = $this->getEntityManager()->createQuery($dql);
		$query->setMaxResults($limit);
	
		return $query->getResult();
		
	}

	public function findAllOrderedByName()
	{
		/*
		$em = $this->getEntityManager();
		$query = $em->createQuery('Select c.nombre from PBVentasBundle:Cliente c ')->setMaxResults(1);
		
		try {
			$product = $query->getSingleResult();
		} catch (\Doctrine\Orm\NoResultException $e) {
			$product = null;
		}
		*/
	}
}