<?php

namespace PB\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaBRepository extends EntityRepository
{
}
