<?php

namespace PB\VentasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioRepository extends EntityRepository
{
}
