<?php

namespace PB\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoCompraLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbaranCompraLineaRepository extends EntityRepository
{
	
}