<?php

namespace PB\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Yaml\Parser;
use Symfony\Component\Yaml\Exception\ParseException;

/**
 * PedidoCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends EntityRepository
{
	function getTipoproveedor(){
		
	}
	private $tipoproveedortag;
	
	public function getTipoProveedorTag(){
		$yaml = new Parser();
		try {
			$value = $yaml->parse(file_get_contents(__DIR__ . '/../Resources/config/compras.yml'));
		} catch (ParseException $e) {
			printf("Unable to parse the YAML string: %s", $e->getMessage());
		}
		 
		$tipos = $value['tipo_proveedor'];
		$this->tipoproveedortag = $tipos[$this->tipo_proveedor];
	}

}