<?php

namespace PB\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoCompraLineaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoCompraLineaRepository extends EntityRepository
{
}