<?php

namespace PB\ComprasBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * PedidoCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends EntityRepository
{

}