PB\AlmacenBundle\Entity\Almacen:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        referencia:
            type: string
            length: 255
            nullable: true
        descripcion:
            type: string
            length: 255
            nullable: true
        cantidad:
            type: float
            length: 255
        paquete:
            type: string
            length: 255
            nullable: true
        serie:
            type: string
            length: 255
        fecha_entrada:
            type: date
            nullable: true
        ancho:
            type: integer
            nullable: true
        largo: 
            type: integer
            nullable: true
        galga: 
            type: integer
            nullable: true
        ubicacion:
            type: string
            lenght: 255
            nullable: true
        estanteria:
            type: string
            lenght: 55
            nullable: true
        nivel:    
            type: string
            lenght: 55
            nullable: true
        posicion:    
            type: string
            lenght: 55
            nullable: true
    manyToOne:
        producto:
            targetEntity: PB\AlmacenBundle\Entity\Producto
            inversedBy: almacen
            joinColumn:
              name: producto_id
              referencedColumnName: id
        albarancompralinea:
            targetEntity: PB\ComprasBundle\Entity\AlbaranCompraLinea
            inversedBy: almacen
            joinColumn:
              name: albarancompralinea_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
