extrusion:
    pattern:  /
    defaults: { _controller: "PBProduccionBundle:Extrusion:index" }
 
anadir_trabajo_extrusion:
    pattern:  /anadir-trabajo
    defaults: { _controller: "PBProduccionBundle:Extrusion:anadirTrabajo" }