PBVentasBundle_homepage:
    pattern:  /
    defaults: { _controller: PBVentasBundle:Default:index }
    
PBVentasBundle_cliente:
    resource: "@PBVentasBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente
    
PBVentasBundle_pedido:
        resource: "@PBVentasBundle/Resources/config/routing/pedido.yml"
        prefix:   /pedido
 
PBVentasBundle_albaran:
        resource: "@PBVentasBundle/Resources/config/routing/albaran.yml"
        prefix:   /albaran
        
PBVentasBundle_comercial:
        resource: "@PBVentasBundle/Resources/config/routing/comercial.yml"
        prefix:   /comercial

PBVentasBundle_precio:
        resource: "@PBVentasBundle/Resources/config/routing/precio.yml"
        prefix:   /precio

PBVentasBundle_albaran:
        resource: "@PBVentasBundle/Resources/config/routing/albaran.yml"
        prefix:   /albaran

PBVentasBundle_factura:
        resource: "@PBVentasBundle/Resources/config/routing/factura.yml"
        prefix:   /factura

PBVentasBundle_facturab:
        resource: "@PBVentasBundle/Resources/config/routing/facturab.yml"
        prefix:   /facturab

PBVentasBundle_presupuesto:
        resource: "@PBVentasBundle/Resources/config/routing/presupuesto.yml"
        prefix:   /presupuesto
