PBVentasBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: PBVentasBundle:Default:index }
    
PBVentasBundle_cliente:
    resource: "@PBVentasBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente
    
PBVentasBundle_pedido:
        resource: "@PBVentasBundle/Resources/config/routing/pedido.yml"
        prefix:   /pedido
 
PBVentasBundle_albaran:
        resource: "@PBVentasBundle/Resources/config/routing/albaran.yml"
        prefix:   /albaran
        
PBVentasBundle_comercial:
        resource: "@PBVentasBundle/Resources/config/routing/comercial.yml"
        prefix:   /comercial

PBVentasBundle_precio:
        resource: "@PBVentasBundle/Resources/config/routing/precio.yml"
        prefix:   /precio

PBVentasBundle_albaran:
        resource: "@PBVentasBundle/Resources/config/routing/albaran.yml"
        prefix:   /albaran
        