parameters:
#    pb_ventas.example.class: PB\VentasBundle\Example

services:
#    pb_ventas.example:
#        class: %pb_ventas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
