parameters:
#    pb_ventas.print_precios.class: PB\VentasBundle\DependencyInyection\Printprecios
     ventas.id: 1

services:
    ventas.print_pedido:
        class: PB\VentasBundle\Printer\PrintPedidoFPDF
        arguments:
            em: @doctrine  
    ventas.print_albaran:
        class: PB\VentasBundle\Printer\PrintAlbaranFPDF
        arguments:
            em: @doctrine
    ventas.print_precios:
        class: PB\VentasBundle\DependencyInjection\Printprecios
        arguments:
        #    entityManager: "@doctrine.orm.entity_manager"
        #    id: %ventas.id%
            em: @doctrine

#    pb_ventas.example:
#        class: %pb_ventas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ventas.type.cliente_id:
        class: PB\VentasBundle\Form\Type\ClienteIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: cliente_text }