parameters:
#    pb_ventas.example.class: PB\VentasBundle\Example

services:
#    pb_ventas.example:
#        class: %pb_ventas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pb_ventas.type.cliente_id:
        class: PB\VentasBundle\Form\Type\ClienteIdType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: cliente_text }
