PB\VentasBundle\Entity\Cliente:
    properties:
        nombre:
            - NotBlank: ~
            - MinLength: 3
        nif: 
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        localidad:
            - NotBlank: ~
        cp:
            - NotBlank: ~ 
        telefono: 
            - NotBlank: ~
        email:
            - Email: ~
PB\VentasBundle\Entity\Comercial:
    properties:
        nombre:
            - NotBlank: ~
            - MinLength: 3
#        telefono:
#            - Type:
#                type: integer
#        fax:
#            - Type:
#                type: integer
#        movil:
#            - Type:
#                type: integer
#                message: "El código de cliente no es un número"
PB\VentasBundle\Entity\Pedido:
    properties:
        cantidad:
            - NotBlank: { message: "El campo Cantidad esta vacio."}
        mtycolor: 
            - NotBlank: { message: "El campo Material y color esta vacio."}
        tipomaterial:
            - NotBlank:  { message: "El campo Tipo Material esta vacio."}
        ancho:
            - NotBlank:  { message: "El campo Ancho esta vacio."}