PB\VentasBundle\Entity\Cliente:
    properties:
        nombre:
            - NotBlank: ~
            - MinLength: 3
        nif: 
            - NotBlank: ~
        direccion:
            - NotBlank: ~
        localidad:
            - NotBlank: ~
        cp:
            - NotBlank: ~ 
        telefono: 
            - NotBlank: ~
        email:
            - Email: ~
#        telefono:
#            - Type:
#                type: integer
#        fax:
#            - Type:
#                type: integer
#        movil:
#            - Type:
#                type: integer
            