tipo_material:
  0: ""
  1: "Bp Opaco Standar"
  2: "Bp Opaco"
  3: "Ap Trp Standar"
  4: "Ap Trp"
  5: "Ap Opaco"
  6: "Bp Trp"
  7: "Bp Color"
  8: "Ap Color"
  9: "Microperforado"
  10: "Polipropileno"
  11: "Papel"

estados_pedidos:
  1: "Nuevo"
  2: "En fabrica"
  3: "Finalizado"
  4: "Facturado"
  8: "Histórico"
  
cliches:
  1: "Nuevo"
  2: "Enviado"
  3: "Repetición"
  4: "Se enviará"
  5: "Rectificación"
  
tipos:
  0: ""
  1: "A"
  2: "B"

estados_facturas:
  1: "No pagada"
  2: "En proceso"
  3: "Pagada"
 
tipo_tubo:
  1: "Tubo"
  2: "Semitubo"
  3: "Lamina"

estados_orden:
  1: "Nuevo"
  2: "Activo"
  3: "Finalizado"

producto:
  1: "Bolsas"
  2: "Bobinas"

tratado:
  1: "Sin Tratar"
  2: "1 Cara"
  3: "2 Cara"

soldadura:
  1: "Camiseta"
  2: "Perlada"
  3: "Caja"
  4: "Saco"
  5: "Fondo"
  6: "Basura"
  10: "Sin Soldadura"

asas:
  1: "Sin Asa"
  2: "Asa Riñon"
  3: "Asa Rígida"