tipo_material:
  0: ""
  1: "Bp Opaco Standar"
  2: "Bp Opaco"
  3: "Ap Trp Standar"
  4: "Ap Trp"
  5: "Ap Opaco"
  6: "Bp Trp"
  7: "Bp Color"
  8: "Ap Color"
  9: "Polipropileno"
  15: "Polipropileno BIO"
  10: "PP Microperforado"
  11: "Ap Trp Microperforado"
  12: "Ap Opaco Microperforado"
  13: "Papel Celulosa"

estados_pedidos:
  1: "Nuevo"
  2: "En fabrica"
  3: "Finalizado"
  4: "Facturado"
  8: "Histórico"
  
cliches:
  1: "Nuevo"
  2: "Enviado"
  3: "Lo Tenemos"
  4: "Se enviarán"
  5: "Rectificación"
  
tipos:
  0: ""
  1: "A"
  2: "B"

estados_facturas:
  1: "No pagada"
  2: "En proceso"
  3: "Pagada"
 
tipo_tubo:
  1: "Tubo"
  2: "Semitubo"
  3: "Lamina"

estados_orden:
  1: "Nuevo"
  2: "En Extrusion"
  3: "En Impresión"
  4: "En Corte"
  5: "En Rebobinado"
  6: "Finalizado"
  8: "Histórico"
producto:
  1: "Bolsas"
  2: "Bobinas"

tratado:
  1: "Sin Tratar"
  2: "1 Caras"
  3: "2 Caras"

soldadura:
  1: "Camiseta"
  2: "Perlada"
  3: "Caja"
  4: "Saco"
  5: "Fondo"
  6: "Basura"
  10: "Sin Soldadura"

asas:
  1: "Sin Asa"
  2: "Asa Riñon"
  3: "Asa Rígida"

estados_incidencias:
  1: "Abierta"
  2: "Cerrada"
