tipo_material:
  1: "Bp Opaco Standar"
  2: "Bp Opaco"
  3: "Ap Trp Standar"
  4: "Ap Trp"
  5: "Ap Opaco"
  6: "Bp Trp"
  7: "Bp Color"
  8: "Ap Color"
  9: "Microperforado"
  10: "Polipropileno"

estados_pedidos:
  1: "Nuevo"
  2: "En fabrica"
  3: "Finalizado"
  4: "Histórico"