pb_general_homepage:
    pattern:  /general
    defaults: { _controller: PBGeneralBundle:Default:index }

PBGeneralBundle_formapago:
    resource: "@PBGeneralBundle/Resources/config/routing/formapago.yml"
    prefix:   /formapago
    