pb_general_homepage:
    pattern:  /
    defaults: { _controller: PBGeneralBundle:Default:index }

PBGeneralBundle_formapago:
    resource: "@PBGeneralBundle/Resources/config/routing/formapago.yml"
    prefix:   /formapago

pb_general_backup:
    pattern:  /backup
    defaults: { _controller: PBGeneralBundle:Backup:index }    